version: "3.7"
services:
    litr:
        build:
            context: ./services/litr/.
            dockerfile: docker/Dockerfile
        ports:
            - "8001:8001"
        environment:
            - AGENT_HOSTNAME=otel-collector
            - OTEL_PYTHON_LOG_CORRELATION=true
        #volumes:
        #    - ./services/litr/app:/app/app
        networks:
            - norse
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.litr.loadbalancer.server.port=5000"
            - "traefik.http.routers.litr.rule=Host(`litr.localhost`)"
            - "traefik.http.routers.litr.entrypoints=web"
            - "app=vtest"
        logging:
            driver: loki
            options:
                loki-url: 'http://localhost:3100/loki/api/v1/push'
                labels: app

    otel-collector:
        image: otel/opentelemetry-collector:latest
        ports:
            - "6831:6831"
            - "14268:14268"
            - "4317:4317"
        volumes:
            - ./config/otel-collector.yaml:/config/otel-collector.yaml
        command:
            - --config=/config/otel-collector.yaml
        networks:
            - norse
        logging:
            driver: loki
            options:
                loki-url: 'http://localhost:3100/api/v1/push'
    
networks:
    norse:
        driver: bridge