version: "3.7"
services:
    traefik:
        image: "traefik:v2.4"
        container_name: "traefik"
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "-providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        networks:
            - norse
        logging:
            driver: loki
            options:
                loki-url: 'http://localhost:3100/loki/api/v1/push'
    tempo:
        image: grafana/tempo:latest
        command: ["-config.file=/etc/tempo.yaml"]
        ports:
            - "3101:3100"
            - "55680:55680"
        volumes:
            - ./config/tempo.yaml:/etc/tempo.yaml
            - ./data/tempo:/tmp/tempo
        networks:
            - norse
        logging:
            driver: loki
            options:
                loki-url: 'http://localhost:3100/api/v1/push'

    loki:
        image: grafana/loki:latest
        command: ["-config.file=/etc/loki/local-config.yaml"]
        ports:
            - "3100:3100"
        environment:
            - JAEGER_AGENT_HOST=tempo
            - JAEGER_ENDPOINT=http://tempo:14258/api/traces
            - JAEGER_SAMPLER_TYPE=const
            - JAEGER_SAMPLER_PARAM=1
        networks:
            - norse
        logging:
            driver: loki
            options:
                loki-url: 'http://localhost:3100/api/v1/push'
    grafana:
        image: grafana/grafana:7.5.4
        volumes:
            - ./config/datasources:/etc/grafana/provisioning/datasources
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        ports:
            - "3000:3000"
        networks:
            - norse
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.grafana.loadbalancer.server.port=3000"
            - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
            - "traefik.http.routers.grafana.entrypoints=web"
        logging:
            driver: loki
            options:
                loki-url: 'http://localhost:3100/api/v1/push'
        
networks:
    norse:
        driver: bridge